FROM alpine

RUN apk update && apk add --no-cache binutils cmake make libgcc \
        musl-dev gcc libarchive-static libarchive-dev acl-static xz-dev lz4-static \
        zstd-static zlib-static openssl-libs-static bzip2-static bzip2-dev expat-static

